extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/strict-type-checked"
  - "plugin:@typescript-eslint/stylistic-type-checked"
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  tsconfigRootDir: "./"
plugins:
  - "@typescript-eslint"
