export const ONE_MINUTE_IN_SECONDS = 60;
export const ONE_HOUR_IN_SECONDS = ONE_MINUTE_IN_SECONDS * 60;

export const ONE_SECOND_IN_MILISECONDS = 1000;
export const ONE_HOUR_IN_MILISECONDS =
  ONE_HOUR_IN_SECONDS * ONE_SECOND_IN_MILISECONDS;
